{
 "title": "Docker - Loki container logs",
 "description": "Dashboard for logs with Alloy and Loki",
 "tags": [
  "loki",
  "logs",
  "docker"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs Count per level",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (\r\n  count_over_time({job=\"docker\"}[$__range])\r\n)"
    }
   ]
  },
  {
   "title": "Logs Volume",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (\r\n  count_over_time({job=\"docker\"}[$__interval])\r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\"} |= \"$filter\""
    }
   ]
  }
 ]
}